const OOO = [
  {
    name: 'Out of Order 1',
    nick: 'OUT_OF_ORDER_1',
    biome: 'hilbertDelta',
    x: 10,
    y: -10,
    requirements: ['TWO_BESIDE'],
    defaultExpression: '0',
    goals: [
      {
        x: 16,
        y: 0,
        order: 'A',
      },
      {
        x: 8,
        y: 0,
        order: 'B',
      },
    ],
    sledders: [{}],
  },
  {
    name: 'Out of Order 2',
    nick: 'OUT_OF_ORDER_2',
    biome: 'hilbertDelta',
    x: 0,
    y: -20,
    requirements: null,
    defaultExpression: '0',
    goals: [
      {
        x: 24,
        y: 0,
        order: 'A',
      },
      {
        x: 8,
        y: 0,
        order: 'B',
      },
      {
        x: 16,
        y: 0,
        order: 'C',
      },
    ],
    sledders: [{}],
  },
  {
    name: 'Out of Order 3',
    nick: 'OUT_OF_ORDER_3',
    biome: 'hilbertDelta',
    x: 10,
    y: 0,
    requirements: null,
    defaultExpression: '0',
    goals: [
      {
        x: 18,
        y: 0,
        order: 'A',
      },
      {
        x: 6,
        y: 0,
        order: 'B',
      },
      {
        x: 24,
        y: 0,
        order: 'C',
      },
      {
        x: 12,
        y: 0,
        order: 'D',
      },
    ],
    sledders: [{}],
  },
  {
    name: 'Out of Order 4',
    nick: 'OUT_OF_ORDER_4',
    biome: 'hilbertDelta',
    x: -10,
    y: -10,
    requirements: ['OUT_OF_ORDER_2'],
    defaultExpression: '0',
    goals: [
      {
        x: -8,
        y: 0,
        order: 'A',
      },
      {
        x: -4,
        y: 0,
        order: 'B',
      },
      {
        x: 4,
        y: 0,
        order: 'B',
      },
      {
        x: 8,
        y: 0,
        order: 'A',
      },
    ],
    sledders: [
      {
        speech: [
          {
            distance: 1.5,
            speakerX: 0.5,
            speakerY: 0.7,
            color: '#FFF',
            direction: 'up-up-right',
            content: 'Pi creature!',
          },
          {
            distance: 2.2,
            speakerX: -0.3,
            speakerY: 0.55,
            color: '#FFF',
            content: 'omigosh!!',
            direction: 'up-up-left',
            align: 'right',
          },
        ],
      },
    ],
    sprites: [
      {
        asset: 'images.pi_dance_kick',
        flipX: false,
        drawOrder: LAYERS.foreSprites,
        size: 1.4,
        x: 6,
        y: 0,
        offset: [0, 0.9],
        sloped: true,
        anchored: true,
        speech: {
          x: 0.2,
          y: 1.2,
          color: '#FFF',
          content: '*meep*',
          direction: 'up-up-right',
          distance: 0.8,
        },
      },
    ],
  },
  {
    name: 'Out of Order 5',
    nick: 'OUT_OF_ORDER_5',
    biome: 'hilbertDelta',
    x: -10,
    y: 0,
    requirements: null,
    defaultExpression: '0',
    goals: [
      {
        x: -12,
        y: 0,
        order: 'C',
      },
      {
        x: -8,
        y: 0,
        order: 'A',
      },
      {
        x: -4,
        y: 0,
        order: 'B',
      },
      {
        x: 4,
        y: 0,
        order: 'B',
      },
      {
        x: 8,
        y: 0,
        order: 'A',
      },
      {
        x: 12,
        y: 0,
        order: 'C',
      },
    ],
    sledders: [
      {
        speech: [
          {
            distance: 2.2,
            speakerX: 0.5,
            speakerY: 0.7,
            color: '#FFF',
            direction: 'up-up-right',
            content: 'How majestic…',
          },
          {
            distance: 1.5,
            speakerX: -0.3,
            speakerY: 0.55,
            color: '#FFF',
            content: 'eee!!',
            direction: 'up-up-left',
            align: 'right',
          },
        ],
      },
    ],
    sprites: [
      {
        asset: 'images.pi_confused',
        flipX: false,
        drawOrder: LAYERS.foreSprites,
        size: 1.4,
        x: 10,
        y: 0,
        offset: [0, 0.9],
        sloped: true,
        anchored: true,
        // speech: {
        //   x: 0.2,
        //   y: 1.2,
        //   color: '#FFF',
        //   content: '…',
        //   direction: 'up-up-right',
        //   distance: 0.8,
        // },
      },
    ],
  },
  {
    name: 'Out of Order 6',
    nick: 'OUT_OF_ORDER_6',
    biome: 'hilbertDelta',
    x: 10,
    y: -10,
    requirements: ['OUT_OF_ORDER_2'],
    defaultExpression: '0',
    goals: [
      {
        x: -6,
        y: 0,
        order: 'C',
      },
      {
        x: -3,
        y: 0,
        order: 'A',
      },
      {
        x: 0,
        y: 0,
        order: 'B',
      },
      {
        x: 3,
        y: 0,
        order: 'A',
      },
      {
        x: 6,
        y: 0,
        order: 'C',
      },
    ],
    sledders: [
      { x: -12, y: 0, asset: 'images.sam_sled' },
      { x: 12, y: 0, asset: 'images.lunchbox_sled' },
    ],
  },
]
